@startuml


title GPU Event Processing at Riskhub (Future State - Kafka Integration)

participant "GPU" as GPU
participant "IPS" as IPS
participant "FISERV" as FISERV
participant "EWS_CRUD" as EWS_CRUD
queue "GPU Event Kafka Topic" as EventHUB #FFD8A8

participant "RH Microservices" as RH_Microservices #F3A3A3
database "MS Eventinfo Table" as MS_Eventinfo #LightBlue
participant "Dedup Logic" as Dedup_Logic
queue "Riskhub Event Kafka Topic" as Kafka_Topic #FFD8A8
participant "PEGA" as PEGA #C7B4DE

participant "Oracle & Mongo CRUD" as Oracle_Mongo_CRUD
participant "Strategy" as Strategy
participant "postStrategy" as postStrategy

GPU -> IPS : Send THD CRC/PROX Fusion Payment Info
IPS -> GPU : send Enriched Payment Info
IPS -> FISERV : send OTB release request
GPU -> EWS_CRUD : Get EWS information
GPU -> EventHUB : publish CRC/PROX consolidated payment & EWS information as Event

' Reverse arrow pointing left to emphasize consumer pulling/polling from the topic
RH_Microservices -> EventHUB : Poll & Consume Event (Pull)

RH_Microservices -> MS_Eventinfo : Insert Event Info

' Future State: Moved from PEGA to RH Microservices
RH_Microservices -> RH_Microservices : Data Translation & Standardization
RH_Microservices -> Dedup_Logic : Execute Deduplication Logic

RH_Microservices -> Kafka_Topic : Publish Standardized & Deduped Event Data (Produce)

' Reverse arrow pointing left to emphasize consumer pulling/polling from the topic
PEGA -> Kafka_Topic : Poll & Consume Event Data (Pull)

PEGA -> Oracle_Mongo_CRUD : Collect & Format required Data based on Dedup result

PEGA -> Strategy : Execute Strategy
PEGA -> postStrategy : Execute postStrategy steps

@enduml
